**Part 1 - Data Preprocessing**

**Import Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Import Dataset**

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[ : , 3:13].values
y = dataset.iloc[ : , 13].values

**Encode Catagorical Data**

**encode independent catagorical data**

In [3]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

#there is 2 column to encode, we took them individually by
#labelencoder_X_1 and labelencoder_X_2 

labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])

#avoid dummy variable trap
#apply onehotencoder on country, because gender will not create a dummy variable trap
#because it contains only 2 catagory where country contains 3

from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('endoding' , OneHotEncoder(), [1])] , remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


**FeatureScaling**

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

**Splitting dataset into train and test**

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

**Part 2- Make ANN**

**Import keras libraries and packages**

In [6]:
import keras
from keras.models import Sequential
from keras.layers import Dense

**Initializing ANN**

In [7]:
classifier = Sequential()

**Adding input layer and first hidden layer**

In [15]:
classifier.add(Dense(6, kernel_initializer='uniform', activation = 'relu', input_dim = 12))

**Adding 2nd hidden layer**

In [16]:
classifier.add(Dense(6, kernel_initializer='uniform', activation = 'relu'))

**Adding output layer**

In [19]:
classifier.add(Dense(1, kernel_initializer='uniform', activation = 'sigmoid'))

**Compiling the ANN**

In [20]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

**Fitting the ANN into Training Set**

In [21]:
classifier.fit(X_train, y_train, batch_size = 5, epochs = 100)

Epoch 1/100
1600/1600 [==============================] - 1s 886us/step - loss: 0.4636 - accuracy: 0.7972
Epoch 2/100
1600/1600 [==============================] - 1s 922us/step - loss: 0.4239 - accuracy: 0.8019
Epoch 3/100
1600/1600 [==============================] - 1s 873us/step - loss: 0.4191 - accuracy: 0.8248
Epoch 4/100
1600/1600 [==============================] - 1s 881us/step - loss: 0.4158 - accuracy: 0.8310
Epoch 5/100
1600/1600 [==============================] - 1s 883us/step - loss: 0.4142 - accuracy: 0.8319
Epoch 6/100
1600/1600 [==============================] - 1s 899us/step - loss: 0.4125 - accuracy: 0.8349
Epoch 7/100
1600/1600 [==============================] - 1s 880us/step - loss: 0.4103 - accuracy: 0.8342
Epoch 8/100
1600/1600 [==============================] - 1s 908us/step - loss: 0.4097 - accuracy: 0.8344
Epoch 9/100
1600/1600 [==============================] - 1s 896us/step - loss: 0.4089 - accuracy: 0.8357
Epoch 10/100
1600/1600 [==============================]

**Part 3 - Predictions and Evaluate the model**

**Predicting the test set results**

In [22]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

**Making the confusion matrix**

In [24]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1549   36]
 [ 292  123]]
